receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  elasticapm: {}

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25

  attributes/sanitize:
    actions:
      - key: http.request.header.authorization
        action: delete
      - key: http.response.header.set-cookie
        action: delete
      - key: user.id
        action: delete

  cumulativetodelta:

  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false

  elasticapm: {}

  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  elasticsearch:
    endpoint: http://elasticsearch:9200
    user: ${env:ELASTICSEARCH_USERNAME}
    password: ${env:ELASTICSEARCH_PASSWORD}
    mapping:
      mode: otel
    sending_queue:
      enabled: true
      sizer: requests
      num_consumers: 10
      queue_size: 100
      block_on_overflow: true
      wait_for_result: false
      batch:
        flush_timeout: 10s
        min_size: 500000
        max_size: 2000000
        sizer: bytes

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, attributes/sanitize, elasticapm, batch]
      exporters: [elasticapm, elasticsearch]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, attributes/sanitize, batch]
      exporters: [elasticsearch]
    metrics/app:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, attributes/sanitize, cumulativetodelta, batch]
      exporters: [elasticsearch]
    metrics/aggregated-apm:
      receivers: [elasticapm]
      processors: [memory_limiter, batch]
      exporters: [elasticsearch]
