entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      port: 21890
      path: /v1/traces
      unframed_requests: true
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  sink:
    - pipeline:
        name: "traces-raw"
    - pipeline:
        name: "service-map"

otel-telemetry:
  source:
    otlp:
      port: 21893
      ssl: false
      unframed_requests: true
      metrics_path: /v1/metrics
      logs_path: /v1/logs
  route:
    - logs: 'getEventType() == "LOG"'
    - metrics: 'getEventType() == "METRIC"'
  sink:
    - opensearch:
        routes:
          - logs
        hosts: ["http://opensearch:9200"]
        index: logs-otel-%{yyyy.MM.dd}
    - pipeline:
        name: "otel-metrics"
        routes:
          - metrics

traces-raw:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - otel_traces:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index_type: trace-analytics-raw

service-map:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - service_map:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index_type: trace-analytics-service-map

otel-metrics:
  source:
    pipeline:
      name: "otel-telemetry"
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: metrics-otel-%{yyyy.MM.dd}
